# This is a basic workflow to help you get started with Actions

name: Deploy to Salesforce Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: main
  pull_request:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    # Install SFDX CLI treu
    - name: Install SFDX CLI
      run: npm install @salesforce/cli --global

    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCEPRODCLIENTID }}
        USERNAME: ${{ secrets.SALESFORCEPRODUSERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCEPRODINSTANCEURL }}
        SERVER_KEY: ${{ secrets.SALESFORCESERVERKEY }}
      run: sfdx force:auth:jwt:grant --client-id $CLIENT_ID --jwt-key-file $SERVER_KEY --username $USERNAME --instance-url $INSTANCE_URL -a dev
      #run: sfdx force:auth:jwt:grant -i $CLIENT_ID -f server.key -u $USERNAME --instance-url $INSTANCE_URL -a dev

    # Convert to Deploy Source
    - name: Convert to Deploy Source
      run: sfdx force:source:convert -r ./force-app -d ./toDeploy
    
    # Run Validation of Deploy Source
    - name: Run Validation on Deploy Source
      run: sfdx force:mdapi:deploy -l RunLocalTests -c -d ./toDeploy -u dev -w 10
    
    # Deploy
    - name : Deploy to SF Org
      run: sfdx force:mdapi:deploy -l RunLocalTests -d ./toDeploy -u dev -w 10